### ISSUE TITLE
How can you achieve the accuracy reported 

### ISSUE THREAD

**Issue by HansiZeng** [Doragd/Text-Classification-PyTorch#1]
For example, I run the TextAttnBiLSTM  model in SST2 dataset  with the following command line, 
python main.py run --status='train' --use_model="TextAttnBiLSTM"

However, I can just get accuracy: 84.295 in the testing set but not 85.632 as you reported. Is anything tricky I miss?

Thanks.

**Comment by Doragd** [comment]
Sorry for misleading you. The project is a toy and out-of-date example about text classification. There may be many factors that make the difference.
